// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "inference.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic inference::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic inference::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<17> inference::ap_ST_fsm_state1 = "1";
const sc_lv<17> inference::ap_ST_fsm_state2 = "10";
const sc_lv<17> inference::ap_ST_fsm_state3 = "100";
const sc_lv<17> inference::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<17> inference::ap_ST_fsm_pp0_stage1 = "10000";
const sc_lv<17> inference::ap_ST_fsm_pp0_stage2 = "100000";
const sc_lv<17> inference::ap_ST_fsm_pp0_stage3 = "1000000";
const sc_lv<17> inference::ap_ST_fsm_pp0_stage4 = "10000000";
const sc_lv<17> inference::ap_ST_fsm_state17 = "100000000";
const sc_lv<17> inference::ap_ST_fsm_state18 = "1000000000";
const sc_lv<17> inference::ap_ST_fsm_state19 = "10000000000";
const sc_lv<17> inference::ap_ST_fsm_pp1_stage0 = "100000000000";
const sc_lv<17> inference::ap_ST_fsm_pp1_stage1 = "1000000000000";
const sc_lv<17> inference::ap_ST_fsm_pp1_stage2 = "10000000000000";
const sc_lv<17> inference::ap_ST_fsm_pp1_stage3 = "100000000000000";
const sc_lv<17> inference::ap_ST_fsm_pp1_stage4 = "1000000000000000";
const sc_lv<17> inference::ap_ST_fsm_state32 = "10000000000000000";
const sc_lv<32> inference::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool inference::ap_const_boolean_1 = true;
const sc_lv<32> inference::ap_const_lv32_3 = "11";
const bool inference::ap_const_boolean_0 = false;
const sc_lv<1> inference::ap_const_lv1_0 = "0";
const sc_lv<32> inference::ap_const_lv32_B = "1011";
const sc_lv<32> inference::ap_const_lv32_1 = "1";
const sc_lv<32> inference::ap_const_lv32_2 = "10";
const sc_lv<32> inference::ap_const_lv32_4 = "100";
const sc_lv<32> inference::ap_const_lv32_9 = "1001";
const sc_lv<32> inference::ap_const_lv32_A = "1010";
const sc_lv<32> inference::ap_const_lv32_C = "1100";
const sc_lv<1> inference::ap_const_lv1_1 = "1";
const sc_lv<32> inference::ap_const_lv32_7 = "111";
const sc_lv<32> inference::ap_const_lv32_5 = "101";
const sc_lv<32> inference::ap_const_lv32_F = "1111";
const sc_lv<5> inference::ap_const_lv5_0 = "00000";
const sc_lv<32> inference::ap_const_lv32_8 = "1000";
const sc_lv<10> inference::ap_const_lv10_0 = "0000000000";
const sc_lv<32> inference::ap_const_lv32_10 = "10000";
const sc_lv<4> inference::ap_const_lv4_0 = "0000";
const sc_lv<32> inference::ap_const_lv32_D = "1101";
const sc_lv<5> inference::ap_const_lv5_10 = "10000";
const sc_lv<5> inference::ap_const_lv5_1 = "1";
const sc_lv<10> inference::ap_const_lv10_310 = "1100010000";
const sc_lv<10> inference::ap_const_lv10_1 = "1";
const sc_lv<32> inference::ap_const_lv32_17 = "10111";
const sc_lv<32> inference::ap_const_lv32_1E = "11110";
const sc_lv<8> inference::ap_const_lv8_FF = "11111111";
const sc_lv<23> inference::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<4> inference::ap_const_lv4_A = "1010";
const sc_lv<4> inference::ap_const_lv4_1 = "1";
const sc_lv<3> inference::ap_const_lv3_0 = "000";
const sc_lv<5> inference::ap_const_lv5_4 = "100";

inference::inference(sc_module_name name) : sc_module(name), mVcdFile(0) {
    b1_U = new inference_b1("b1_U");
    b1_U->clk(ap_clk);
    b1_U->reset(ap_rst);
    b1_U->address0(b1_address0);
    b1_U->ce0(b1_ce0);
    b1_U->q0(b1_q0);
    W1_U = new inference_W1("W1_U");
    W1_U->clk(ap_clk);
    W1_U->reset(ap_rst);
    W1_U->address0(W1_address0);
    W1_U->ce0(W1_ce0);
    W1_U->q0(W1_q0);
    b2_U = new inference_b2("b2_U");
    b2_U->clk(ap_clk);
    b2_U->reset(ap_rst);
    b2_U->address0(b2_address0);
    b2_U->ce0(b2_ce0);
    b2_U->q0(b2_q0);
    W2_U = new inference_W2("W2_U");
    W2_U->clk(ap_clk);
    W2_U->reset(ap_rst);
    W2_U->address0(W2_address0);
    W2_U->ce0(W2_ce0);
    W2_U->q0(W2_q0);
    hidden_U = new inference_hidden("hidden_U");
    hidden_U->clk(ap_clk);
    hidden_U->reset(ap_rst);
    hidden_U->address0(hidden_address0);
    hidden_U->ce0(hidden_ce0);
    hidden_U->we0(hidden_we0);
    hidden_U->d0(hidden_d0);
    hidden_U->q0(hidden_q0);
    inference_fadd_32bkb_U1 = new inference_fadd_32bkb<1,5,32,32,32>("inference_fadd_32bkb_U1");
    inference_fadd_32bkb_U1->clk(ap_clk);
    inference_fadd_32bkb_U1->reset(ap_rst);
    inference_fadd_32bkb_U1->din0(grp_fu_251_p0);
    inference_fadd_32bkb_U1->din1(reg_266);
    inference_fadd_32bkb_U1->ce(ap_var_for_const0);
    inference_fadd_32bkb_U1->dout(grp_fu_251_p2);
    inference_fmul_32cud_U2 = new inference_fmul_32cud<1,4,32,32,32>("inference_fmul_32cud_U2");
    inference_fmul_32cud_U2->clk(ap_clk);
    inference_fmul_32cud_U2->reset(ap_rst);
    inference_fmul_32cud_U2->din0(grp_fu_257_p0);
    inference_fmul_32cud_U2->din1(grp_fu_257_p1);
    inference_fmul_32cud_U2->ce(ap_var_for_const0);
    inference_fmul_32cud_U2->dout(grp_fu_257_p2);
    inference_fcmp_32dEe_U3 = new inference_fcmp_32dEe<1,2,32,32,1>("inference_fcmp_32dEe_U3");
    inference_fcmp_32dEe_U3->clk(ap_clk);
    inference_fcmp_32dEe_U3->reset(ap_rst);
    inference_fcmp_32dEe_U3->din0(reg_271);
    inference_fcmp_32dEe_U3->din1(ap_var_for_const1);
    inference_fcmp_32dEe_U3->ce(ap_var_for_const0);
    inference_fcmp_32dEe_U3->opcode(ap_var_for_const2);
    inference_fcmp_32dEe_U3->dout(grp_fu_261_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_W1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln20_2_fu_335_p1 );

    SC_METHOD(thread_W1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_W2_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln38_3_fu_470_p1 );

    SC_METHOD(thread_W2_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_add_ln20_fu_330_p2);
    sensitive << ( zext_ln15_1_reg_498 );
    sensitive << ( zext_ln20_1_fu_326_p1 );

    SC_METHOD(thread_add_ln38_1_fu_465_p2);
    sensitive << ( zext_ln33_1_reg_560 );
    sensitive << ( add_ln38_fu_459_p2 );

    SC_METHOD(thread_add_ln38_fu_459_p2);
    sensitive << ( zext_ln38_2_fu_455_p1 );
    sensitive << ( zext_ln38_1_fu_443_p1 );

    SC_METHOD(thread_and_ln24_fu_381_p2);
    sensitive << ( or_ln24_fu_375_p2 );
    sensitive << ( grp_fu_261_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_00001);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage1);

    SC_METHOD(thread_ap_block_pp1_stage1_11001);

    SC_METHOD(thread_ap_block_pp1_stage1_subdone);

    SC_METHOD(thread_ap_block_pp1_stage2);

    SC_METHOD(thread_ap_block_pp1_stage2_11001);

    SC_METHOD(thread_ap_block_pp1_stage2_subdone);

    SC_METHOD(thread_ap_block_pp1_stage3_11001);

    SC_METHOD(thread_ap_block_pp1_stage3_subdone);

    SC_METHOD(thread_ap_block_pp1_stage4_11001);

    SC_METHOD(thread_ap_block_pp1_stage4_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state11_pp0_stage2_iter1);

    SC_METHOD(thread_ap_block_state12_pp0_stage3_iter1);

    SC_METHOD(thread_ap_block_state13_pp0_stage4_iter1);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state15_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state16_pp0_stage2_iter2);

    SC_METHOD(thread_ap_block_state20_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state21_pp1_stage1_iter0);

    SC_METHOD(thread_ap_block_state22_pp1_stage2_iter0);

    SC_METHOD(thread_ap_block_state23_pp1_stage3_iter0);

    SC_METHOD(thread_ap_block_state24_pp1_stage4_iter0);

    SC_METHOD(thread_ap_block_state25_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state26_pp1_stage1_iter1);

    SC_METHOD(thread_ap_block_state27_pp1_stage2_iter1);

    SC_METHOD(thread_ap_block_state28_pp1_stage3_iter1);

    SC_METHOD(thread_ap_block_state29_pp1_stage4_iter1);

    SC_METHOD(thread_ap_block_state30_pp1_stage0_iter2);

    SC_METHOD(thread_ap_block_state31_pp1_stage1_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state7_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state8_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( icmp_ln17_fu_301_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state20);
    sensitive << ( icmp_ln35_fu_418_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln31_fu_396_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_ap_phi_mux_i3_0_phi_fu_244_p4);
    sensitive << ( i3_0_reg_240 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( icmp_ln35_reg_570 );
    sensitive << ( i_1_reg_574 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_ap_phi_mux_i_0_phi_fu_201_p4);
    sensitive << ( i_0_reg_197 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln17_reg_508 );
    sensitive << ( i_reg_512 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_sum2_0_phi_fu_233_p4);
    sensitive << ( sum2_0_reg_230 );
    sensitive << ( reg_271 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( icmp_ln35_reg_570_pp1_iter2_reg );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_ap_phi_mux_sum_0_phi_fu_211_p4);
    sensitive << ( sum_0_reg_208 );
    sensitive << ( reg_271 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln17_reg_508_pp0_iter2_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln31_fu_396_p2 );

    SC_METHOD(thread_b1_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln15_fu_291_p1 );

    SC_METHOD(thread_b1_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_b2_address0);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln33_fu_408_p1 );

    SC_METHOD(thread_b2_ce0);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_bitcast_ln24_fu_345_p1);
    sensitive << ( reg_271 );

    SC_METHOD(thread_grp_fu_251_p0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_phi_mux_sum_0_phi_fu_211_p4 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_phi_mux_sum2_0_phi_fu_233_p4 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_grp_fu_257_p0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( W1_load_reg_528 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( W2_load_reg_590 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp1_stage2 );
    sensitive << ( ap_block_pp1_stage2 );

    SC_METHOD(thread_grp_fu_257_p1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( input_load_reg_533 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( hidden_load_reg_595 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp1_stage2 );
    sensitive << ( ap_block_pp1_stage2 );

    SC_METHOD(thread_hidden_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( hidden_addr_reg_493 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp1_stage0 );
    sensitive << ( zext_ln38_fu_430_p1 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_hidden_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_hidden_d0);
    sensitive << ( reg_271 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( and_ln24_fu_381_p2 );

    SC_METHOD(thread_hidden_we0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln17_1_reg_538_pp0_iter2_reg );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_i_1_fu_424_p2);
    sensitive << ( ap_phi_mux_i3_0_phi_fu_244_p4 );

    SC_METHOD(thread_i_fu_307_p2);
    sensitive << ( ap_phi_mux_i_0_phi_fu_201_p4 );

    SC_METHOD(thread_icmp_ln13_fu_279_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( j_0_reg_185 );

    SC_METHOD(thread_icmp_ln17_1_fu_340_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln17_reg_508 );
    sensitive << ( i_reg_512 );

    SC_METHOD(thread_icmp_ln17_fu_301_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_i_0_phi_fu_201_p4 );

    SC_METHOD(thread_icmp_ln24_1_fu_369_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln17_1_reg_538_pp0_iter2_reg );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( trunc_ln24_fu_359_p1 );

    SC_METHOD(thread_icmp_ln24_fu_363_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln17_1_reg_538_pp0_iter2_reg );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( tmp_fu_349_p4 );

    SC_METHOD(thread_icmp_ln31_fu_396_p2);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( j1_0_reg_218 );

    SC_METHOD(thread_icmp_ln35_1_fu_475_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( icmp_ln35_reg_570 );
    sensitive << ( i_1_reg_574 );

    SC_METHOD(thread_icmp_ln35_fu_418_p2);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_phi_mux_i3_0_phi_fu_244_p4 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln20_fu_313_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_j_1_fu_402_p2);
    sensitive << ( j1_0_reg_218 );

    SC_METHOD(thread_j_fu_285_p2);
    sensitive << ( j_0_reg_185 );

    SC_METHOD(thread_or_ln24_fu_375_p2);
    sensitive << ( icmp_ln24_1_fu_369_p2 );
    sensitive << ( icmp_ln24_fu_363_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( output_addr_reg_555 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp1_stage1_11001 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( reg_271 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp1_stage1 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp1_stage1_11001 );
    sensitive << ( icmp_ln35_1_reg_600_pp1_iter2_reg );

    SC_METHOD(thread_tmp_6_fu_318_p3);
    sensitive << ( ap_phi_mux_i_0_phi_fu_201_p4 );

    SC_METHOD(thread_tmp_7_fu_435_p3);
    sensitive << ( ap_phi_mux_i3_0_phi_fu_244_p4 );

    SC_METHOD(thread_tmp_8_fu_447_p3);
    sensitive << ( ap_phi_mux_i3_0_phi_fu_244_p4 );

    SC_METHOD(thread_tmp_fu_349_p4);
    sensitive << ( bitcast_ln24_fu_345_p1 );

    SC_METHOD(thread_trunc_ln24_fu_359_p1);
    sensitive << ( bitcast_ln24_fu_345_p1 );

    SC_METHOD(thread_zext_ln15_1_fu_297_p1);
    sensitive << ( j_0_reg_185 );

    SC_METHOD(thread_zext_ln15_fu_291_p1);
    sensitive << ( j_0_reg_185 );

    SC_METHOD(thread_zext_ln20_1_fu_326_p1);
    sensitive << ( tmp_6_fu_318_p3 );

    SC_METHOD(thread_zext_ln20_2_fu_335_p1);
    sensitive << ( add_ln20_fu_330_p2 );

    SC_METHOD(thread_zext_ln20_fu_313_p1);
    sensitive << ( ap_phi_mux_i_0_phi_fu_201_p4 );

    SC_METHOD(thread_zext_ln33_1_fu_414_p1);
    sensitive << ( j1_0_reg_218 );

    SC_METHOD(thread_zext_ln33_fu_408_p1);
    sensitive << ( j1_0_reg_218 );

    SC_METHOD(thread_zext_ln38_1_fu_443_p1);
    sensitive << ( tmp_7_fu_435_p3 );

    SC_METHOD(thread_zext_ln38_2_fu_455_p1);
    sensitive << ( tmp_8_fu_447_p3 );

    SC_METHOD(thread_zext_ln38_3_fu_470_p1);
    sensitive << ( add_ln38_1_fu_465_p2 );

    SC_METHOD(thread_zext_ln38_fu_430_p1);
    sensitive << ( ap_phi_mux_i3_0_phi_fu_244_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp1_iter2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln13_fu_279_p2 );
    sensitive << ( icmp_ln17_fu_301_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln31_fu_396_p2 );
    sensitive << ( icmp_ln35_fu_418_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_pp1_stage1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp1_stage0_subdone );
    sensitive << ( ap_block_pp1_stage4_subdone );
    sensitive << ( ap_block_pp1_stage1_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );
    sensitive << ( ap_block_pp1_stage2_subdone );
    sensitive << ( ap_block_pp1_stage3_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "00000000000000001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "inference_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, b1_address0, "b1_address0");
    sc_trace(mVcdFile, b1_ce0, "b1_ce0");
    sc_trace(mVcdFile, b1_q0, "b1_q0");
    sc_trace(mVcdFile, W1_address0, "W1_address0");
    sc_trace(mVcdFile, W1_ce0, "W1_ce0");
    sc_trace(mVcdFile, W1_q0, "W1_q0");
    sc_trace(mVcdFile, b2_address0, "b2_address0");
    sc_trace(mVcdFile, b2_ce0, "b2_ce0");
    sc_trace(mVcdFile, b2_q0, "b2_q0");
    sc_trace(mVcdFile, W2_address0, "W2_address0");
    sc_trace(mVcdFile, W2_ce0, "W2_ce0");
    sc_trace(mVcdFile, W2_q0, "W2_q0");
    sc_trace(mVcdFile, i_0_reg_197, "i_0_reg_197");
    sc_trace(mVcdFile, sum_0_reg_208, "sum_0_reg_208");
    sc_trace(mVcdFile, sum2_0_reg_230, "sum2_0_reg_230");
    sc_trace(mVcdFile, i3_0_reg_240, "i3_0_reg_240");
    sc_trace(mVcdFile, grp_fu_257_p2, "grp_fu_257_p2");
    sc_trace(mVcdFile, reg_266, "reg_266");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter1, "ap_block_state9_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter2, "ap_block_state14_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln17_reg_508, "icmp_ln17_reg_508");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, ap_block_state20_pp1_stage0_iter0, "ap_block_state20_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state25_pp1_stage0_iter1, "ap_block_state25_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state30_pp1_stage0_iter2, "ap_block_state30_pp1_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, icmp_ln35_reg_570, "icmp_ln35_reg_570");
    sc_trace(mVcdFile, grp_fu_251_p2, "grp_fu_251_p2");
    sc_trace(mVcdFile, reg_271, "reg_271");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, icmp_ln17_reg_508_pp0_iter1_reg, "icmp_ln17_reg_508_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter2, "ap_enable_reg_pp1_iter2");
    sc_trace(mVcdFile, icmp_ln35_reg_570_pp1_iter1_reg, "icmp_ln35_reg_570_pp1_iter1_reg");
    sc_trace(mVcdFile, j_fu_285_p2, "j_fu_285_p2");
    sc_trace(mVcdFile, j_reg_483, "j_reg_483");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln13_fu_279_p2, "icmp_ln13_fu_279_p2");
    sc_trace(mVcdFile, hidden_addr_reg_493, "hidden_addr_reg_493");
    sc_trace(mVcdFile, zext_ln15_1_fu_297_p1, "zext_ln15_1_fu_297_p1");
    sc_trace(mVcdFile, zext_ln15_1_reg_498, "zext_ln15_1_reg_498");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln17_fu_301_p2, "icmp_ln17_fu_301_p2");
    sc_trace(mVcdFile, icmp_ln17_reg_508_pp0_iter2_reg, "icmp_ln17_reg_508_pp0_iter2_reg");
    sc_trace(mVcdFile, i_fu_307_p2, "i_fu_307_p2");
    sc_trace(mVcdFile, i_reg_512, "i_reg_512");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, W1_load_reg_528, "W1_load_reg_528");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter0, "ap_block_state5_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage1_iter1, "ap_block_state10_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage1_iter2, "ap_block_state15_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, input_load_reg_533, "input_load_reg_533");
    sc_trace(mVcdFile, icmp_ln17_1_fu_340_p2, "icmp_ln17_1_fu_340_p2");
    sc_trace(mVcdFile, icmp_ln17_1_reg_538, "icmp_ln17_1_reg_538");
    sc_trace(mVcdFile, icmp_ln17_1_reg_538_pp0_iter2_reg, "icmp_ln17_1_reg_538_pp0_iter2_reg");
    sc_trace(mVcdFile, j_1_fu_402_p2, "j_1_fu_402_p2");
    sc_trace(mVcdFile, j_1_reg_545, "j_1_reg_545");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, icmp_ln31_fu_396_p2, "icmp_ln31_fu_396_p2");
    sc_trace(mVcdFile, output_addr_reg_555, "output_addr_reg_555");
    sc_trace(mVcdFile, zext_ln33_1_fu_414_p1, "zext_ln33_1_fu_414_p1");
    sc_trace(mVcdFile, zext_ln33_1_reg_560, "zext_ln33_1_reg_560");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, icmp_ln35_fu_418_p2, "icmp_ln35_fu_418_p2");
    sc_trace(mVcdFile, icmp_ln35_reg_570_pp1_iter2_reg, "icmp_ln35_reg_570_pp1_iter2_reg");
    sc_trace(mVcdFile, i_1_fu_424_p2, "i_1_fu_424_p2");
    sc_trace(mVcdFile, i_1_reg_574, "i_1_reg_574");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, W2_load_reg_590, "W2_load_reg_590");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage1, "ap_CS_fsm_pp1_stage1");
    sc_trace(mVcdFile, ap_block_state21_pp1_stage1_iter0, "ap_block_state21_pp1_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state26_pp1_stage1_iter1, "ap_block_state26_pp1_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state31_pp1_stage1_iter2, "ap_block_state31_pp1_stage1_iter2");
    sc_trace(mVcdFile, ap_block_pp1_stage1_11001, "ap_block_pp1_stage1_11001");
    sc_trace(mVcdFile, hidden_q0, "hidden_q0");
    sc_trace(mVcdFile, hidden_load_reg_595, "hidden_load_reg_595");
    sc_trace(mVcdFile, icmp_ln35_1_fu_475_p2, "icmp_ln35_1_fu_475_p2");
    sc_trace(mVcdFile, icmp_ln35_1_reg_600, "icmp_ln35_1_reg_600");
    sc_trace(mVcdFile, icmp_ln35_1_reg_600_pp1_iter2_reg, "icmp_ln35_1_reg_600_pp1_iter2_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage4_iter0, "ap_block_state8_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage4_iter1, "ap_block_state13_pp0_stage4_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage2_iter0, "ap_block_state6_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage2_iter1, "ap_block_state11_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage2_iter2, "ap_block_state16_pp0_stage2_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state20, "ap_condition_pp1_exit_iter0_state20");
    sc_trace(mVcdFile, ap_block_state24_pp1_stage4_iter0, "ap_block_state24_pp1_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state29_pp1_stage4_iter1, "ap_block_state29_pp1_stage4_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage4_subdone, "ap_block_pp1_stage4_subdone");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage4, "ap_CS_fsm_pp1_stage4");
    sc_trace(mVcdFile, ap_block_pp1_stage1_subdone, "ap_block_pp1_stage1_subdone");
    sc_trace(mVcdFile, hidden_address0, "hidden_address0");
    sc_trace(mVcdFile, hidden_ce0, "hidden_ce0");
    sc_trace(mVcdFile, hidden_we0, "hidden_we0");
    sc_trace(mVcdFile, hidden_d0, "hidden_d0");
    sc_trace(mVcdFile, j_0_reg_185, "j_0_reg_185");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_phi_mux_i_0_phi_fu_201_p4, "ap_phi_mux_i_0_phi_fu_201_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_sum_0_phi_fu_211_p4, "ap_phi_mux_sum_0_phi_fu_211_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, j1_0_reg_218, "j1_0_reg_218");
    sc_trace(mVcdFile, ap_CS_fsm_state32, "ap_CS_fsm_state32");
    sc_trace(mVcdFile, ap_phi_mux_sum2_0_phi_fu_233_p4, "ap_phi_mux_sum2_0_phi_fu_233_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage1, "ap_block_pp1_stage1");
    sc_trace(mVcdFile, ap_phi_mux_i3_0_phi_fu_244_p4, "ap_phi_mux_i3_0_phi_fu_244_p4");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, zext_ln15_fu_291_p1, "zext_ln15_fu_291_p1");
    sc_trace(mVcdFile, zext_ln20_2_fu_335_p1, "zext_ln20_2_fu_335_p1");
    sc_trace(mVcdFile, zext_ln20_fu_313_p1, "zext_ln20_fu_313_p1");
    sc_trace(mVcdFile, zext_ln33_fu_408_p1, "zext_ln33_fu_408_p1");
    sc_trace(mVcdFile, zext_ln38_3_fu_470_p1, "zext_ln38_3_fu_470_p1");
    sc_trace(mVcdFile, zext_ln38_fu_430_p1, "zext_ln38_fu_430_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, grp_fu_251_p0, "grp_fu_251_p0");
    sc_trace(mVcdFile, grp_fu_257_p0, "grp_fu_257_p0");
    sc_trace(mVcdFile, grp_fu_257_p1, "grp_fu_257_p1");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage2, "ap_CS_fsm_pp1_stage2");
    sc_trace(mVcdFile, ap_block_pp1_stage2, "ap_block_pp1_stage2");
    sc_trace(mVcdFile, tmp_6_fu_318_p3, "tmp_6_fu_318_p3");
    sc_trace(mVcdFile, zext_ln20_1_fu_326_p1, "zext_ln20_1_fu_326_p1");
    sc_trace(mVcdFile, add_ln20_fu_330_p2, "add_ln20_fu_330_p2");
    sc_trace(mVcdFile, bitcast_ln24_fu_345_p1, "bitcast_ln24_fu_345_p1");
    sc_trace(mVcdFile, tmp_fu_349_p4, "tmp_fu_349_p4");
    sc_trace(mVcdFile, trunc_ln24_fu_359_p1, "trunc_ln24_fu_359_p1");
    sc_trace(mVcdFile, icmp_ln24_1_fu_369_p2, "icmp_ln24_1_fu_369_p2");
    sc_trace(mVcdFile, icmp_ln24_fu_363_p2, "icmp_ln24_fu_363_p2");
    sc_trace(mVcdFile, or_ln24_fu_375_p2, "or_ln24_fu_375_p2");
    sc_trace(mVcdFile, grp_fu_261_p2, "grp_fu_261_p2");
    sc_trace(mVcdFile, and_ln24_fu_381_p2, "and_ln24_fu_381_p2");
    sc_trace(mVcdFile, tmp_7_fu_435_p3, "tmp_7_fu_435_p3");
    sc_trace(mVcdFile, tmp_8_fu_447_p3, "tmp_8_fu_447_p3");
    sc_trace(mVcdFile, zext_ln38_2_fu_455_p1, "zext_ln38_2_fu_455_p1");
    sc_trace(mVcdFile, zext_ln38_1_fu_443_p1, "zext_ln38_1_fu_443_p1");
    sc_trace(mVcdFile, add_ln38_fu_459_p2, "add_ln38_fu_459_p2");
    sc_trace(mVcdFile, add_ln38_1_fu_465_p2, "add_ln38_1_fu_465_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_00001, "ap_block_pp0_stage1_00001");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage3_iter0, "ap_block_state7_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage3_iter1, "ap_block_state12_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, ap_block_state22_pp1_stage2_iter0, "ap_block_state22_pp1_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state27_pp1_stage2_iter1, "ap_block_state27_pp1_stage2_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage2_subdone, "ap_block_pp1_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp1_stage2_11001, "ap_block_pp1_stage2_11001");
    sc_trace(mVcdFile, ap_block_state23_pp1_stage3_iter0, "ap_block_state23_pp1_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state28_pp1_stage3_iter1, "ap_block_state28_pp1_stage3_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage3_subdone, "ap_block_pp1_stage3_subdone");
    sc_trace(mVcdFile, ap_block_pp1_stage3_11001, "ap_block_pp1_stage3_11001");
    sc_trace(mVcdFile, ap_block_pp1_stage4_11001, "ap_block_pp1_stage4_11001");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
    mHdltvinHandle.open("inference.hdltvin.dat");
    mHdltvoutHandle.open("inference.hdltvout.dat");
}

inference::~inference() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete b1_U;
    delete W1_U;
    delete b2_U;
    delete W2_U;
    delete hidden_U;
    delete inference_fadd_32bkb_U1;
    delete inference_fmul_32cud_U2;
    delete inference_fcmp_32dEe_U3;
}

void inference::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void inference::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_0;
}

void inference::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv5_4;
}

void inference::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read())) || 
             (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read())))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state20.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage4.read()))) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter2 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage4.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp1_iter2 = ap_enable_reg_pp1_iter1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
            ap_enable_reg_pp1_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570.read()))) {
        i3_0_reg_240 = i_1_reg_574.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        i3_0_reg_240 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln17_reg_508.read(), ap_const_lv1_0))) {
        i_0_reg_197 = i_reg_512.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_0_reg_197 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln13_fu_279_p2.read(), ap_const_lv1_1))) {
        j1_0_reg_218 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state32.read())) {
        j1_0_reg_218 = j_1_reg_545.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        j_0_reg_185 = j_reg_483.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_reg_185 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570_pp1_iter2_reg.read()))) {
        sum2_0_reg_230 = reg_271.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        sum2_0_reg_230 = b2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_508_pp0_iter2_reg.read()))) {
        sum_0_reg_208 = reg_271.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sum_0_reg_208 = b1_q0.read();
    }
    if ((esl_seteq<1,1,1>(icmp_ln17_reg_508.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        W1_load_reg_528 = W1_q0.read();
        input_load_reg_533 = input_r_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0))) {
        W2_load_reg_590 = W2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln13_fu_279_p2.read()))) {
        hidden_addr_reg_493 =  (sc_lv<4>) (zext_ln15_fu_291_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0))) {
        hidden_load_reg_595 = hidden_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        i_1_reg_574 = i_1_fu_424_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        i_reg_512 = i_fu_307_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln17_reg_508.read(), ap_const_lv1_0))) {
        icmp_ln17_1_reg_538 = icmp_ln17_1_fu_340_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln17_1_reg_538_pp0_iter2_reg = icmp_ln17_1_reg_538.read();
        icmp_ln17_reg_508 = icmp_ln17_fu_301_p2.read();
        icmp_ln17_reg_508_pp0_iter1_reg = icmp_ln17_reg_508.read();
        icmp_ln17_reg_508_pp0_iter2_reg = icmp_ln17_reg_508_pp0_iter1_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570.read()))) {
        icmp_ln35_1_reg_600 = icmp_ln35_1_fu_475_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln35_1_reg_600_pp1_iter2_reg = icmp_ln35_1_reg_600.read();
        icmp_ln35_reg_570 = icmp_ln35_fu_418_p2.read();
        icmp_ln35_reg_570_pp1_iter1_reg = icmp_ln35_reg_570.read();
        icmp_ln35_reg_570_pp1_iter2_reg = icmp_ln35_reg_570_pp1_iter1_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        j_1_reg_545 = j_1_fu_402_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        j_reg_483 = j_fu_285_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln31_fu_396_p2.read()))) {
        output_addr_reg_555 =  (sc_lv<4>) (zext_ln33_fu_408_p1.read());
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln17_reg_508.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570.read())))) {
        reg_266 = grp_fu_257_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_508_pp0_iter1_reg.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570_pp1_iter1_reg.read())))) {
        reg_271 = grp_fu_251_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        zext_ln15_1_reg_498 = zext_ln15_1_fu_297_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        zext_ln33_1_reg_560 = zext_ln33_1_fu_414_p1.read();
    }
}

void inference::thread_W1_address0() {
    W1_address0 =  (sc_lv<14>) (zext_ln20_2_fu_335_p1.read());
}

void inference::thread_W1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        W1_ce0 = ap_const_logic_1;
    } else {
        W1_ce0 = ap_const_logic_0;
    }
}

void inference::thread_W2_address0() {
    W2_address0 =  (sc_lv<8>) (zext_ln38_3_fu_470_p1.read());
}

void inference::thread_W2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        W2_ce0 = ap_const_logic_1;
    } else {
        W2_ce0 = ap_const_logic_0;
    }
}

void inference::thread_add_ln20_fu_330_p2() {
    add_ln20_fu_330_p2 = (!zext_ln15_1_reg_498.read().is_01() || !zext_ln20_1_fu_326_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(zext_ln15_1_reg_498.read()) + sc_biguint<15>(zext_ln20_1_fu_326_p1.read()));
}

void inference::thread_add_ln38_1_fu_465_p2() {
    add_ln38_1_fu_465_p2 = (!add_ln38_fu_459_p2.read().is_01() || !zext_ln33_1_reg_560.read().is_01())? sc_lv<9>(): (sc_biguint<9>(add_ln38_fu_459_p2.read()) + sc_biguint<9>(zext_ln33_1_reg_560.read()));
}

void inference::thread_add_ln38_fu_459_p2() {
    add_ln38_fu_459_p2 = (!zext_ln38_2_fu_455_p1.read().is_01() || !zext_ln38_1_fu_443_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln38_2_fu_455_p1.read()) + sc_biguint<9>(zext_ln38_1_fu_443_p1.read()));
}

void inference::thread_and_ln24_fu_381_p2() {
    and_ln24_fu_381_p2 = (or_ln24_fu_375_p2.read() & grp_fu_261_p2.read());
}

void inference::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void inference::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[4];
}

void inference::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[5];
}

void inference::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[7];
}

void inference::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[11];
}

void inference::thread_ap_CS_fsm_pp1_stage1() {
    ap_CS_fsm_pp1_stage1 = ap_CS_fsm.read()[12];
}

void inference::thread_ap_CS_fsm_pp1_stage2() {
    ap_CS_fsm_pp1_stage2 = ap_CS_fsm.read()[13];
}

void inference::thread_ap_CS_fsm_pp1_stage4() {
    ap_CS_fsm_pp1_stage4 = ap_CS_fsm.read()[15];
}

void inference::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void inference::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[8];
}

void inference::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[9];
}

void inference::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[10];
}

void inference::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void inference::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void inference::thread_ap_CS_fsm_state32() {
    ap_CS_fsm_state32 = ap_CS_fsm.read()[16];
}

void inference::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage1_00001() {
    ap_block_pp0_stage1_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage1() {
    ap_block_pp1_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage1_11001() {
    ap_block_pp1_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage1_subdone() {
    ap_block_pp1_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage2() {
    ap_block_pp1_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage2_11001() {
    ap_block_pp1_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage2_subdone() {
    ap_block_pp1_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage3_11001() {
    ap_block_pp1_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage3_subdone() {
    ap_block_pp1_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage4_11001() {
    ap_block_pp1_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_pp1_stage4_subdone() {
    ap_block_pp1_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state10_pp0_stage1_iter1() {
    ap_block_state10_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state11_pp0_stage2_iter1() {
    ap_block_state11_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state12_pp0_stage3_iter1() {
    ap_block_state12_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state13_pp0_stage4_iter1() {
    ap_block_state13_pp0_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state14_pp0_stage0_iter2() {
    ap_block_state14_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state15_pp0_stage1_iter2() {
    ap_block_state15_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state16_pp0_stage2_iter2() {
    ap_block_state16_pp0_stage2_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state20_pp1_stage0_iter0() {
    ap_block_state20_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state21_pp1_stage1_iter0() {
    ap_block_state21_pp1_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state22_pp1_stage2_iter0() {
    ap_block_state22_pp1_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state23_pp1_stage3_iter0() {
    ap_block_state23_pp1_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state24_pp1_stage4_iter0() {
    ap_block_state24_pp1_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state25_pp1_stage0_iter1() {
    ap_block_state25_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state26_pp1_stage1_iter1() {
    ap_block_state26_pp1_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state27_pp1_stage2_iter1() {
    ap_block_state27_pp1_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state28_pp1_stage3_iter1() {
    ap_block_state28_pp1_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state29_pp1_stage4_iter1() {
    ap_block_state29_pp1_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state30_pp1_stage0_iter2() {
    ap_block_state30_pp1_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state31_pp1_stage1_iter2() {
    ap_block_state31_pp1_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state5_pp0_stage1_iter0() {
    ap_block_state5_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state6_pp0_stage2_iter0() {
    ap_block_state6_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state7_pp0_stage3_iter0() {
    ap_block_state7_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state8_pp0_stage4_iter0() {
    ap_block_state8_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_block_state9_pp0_stage0_iter1() {
    ap_block_state9_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void inference::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(icmp_ln17_fu_301_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void inference::thread_ap_condition_pp1_exit_iter0_state20() {
    if (esl_seteq<1,1,1>(icmp_ln35_fu_418_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp1_exit_iter0_state20 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state20 = ap_const_logic_0;
    }
}

void inference::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_396_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void inference::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void inference::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void inference::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void inference::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void inference::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter2.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void inference::thread_ap_phi_mux_i3_0_phi_fu_244_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i3_0_phi_fu_244_p4 = i_1_reg_574.read();
    } else {
        ap_phi_mux_i3_0_phi_fu_244_p4 = i3_0_reg_240.read();
    }
}

void inference::thread_ap_phi_mux_i_0_phi_fu_201_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln17_reg_508.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_0_phi_fu_201_p4 = i_reg_512.read();
    } else {
        ap_phi_mux_i_0_phi_fu_201_p4 = i_0_reg_197.read();
    }
}

void inference::thread_ap_phi_mux_sum2_0_phi_fu_233_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln35_reg_570_pp1_iter2_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_sum2_0_phi_fu_233_p4 = reg_271.read();
    } else {
        ap_phi_mux_sum2_0_phi_fu_233_p4 = sum2_0_reg_230.read();
    }
}

void inference::thread_ap_phi_mux_sum_0_phi_fu_211_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_reg_508_pp0_iter2_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_sum_0_phi_fu_211_p4 = reg_271.read();
    } else {
        ap_phi_mux_sum_0_phi_fu_211_p4 = sum_0_reg_208.read();
    }
}

void inference::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
         esl_seteq<1,1,1>(icmp_ln31_fu_396_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void inference::thread_b1_address0() {
    b1_address0 =  (sc_lv<4>) (zext_ln15_fu_291_p1.read());
}

void inference::thread_b1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        b1_ce0 = ap_const_logic_1;
    } else {
        b1_ce0 = ap_const_logic_0;
    }
}

void inference::thread_b2_address0() {
    b2_address0 =  (sc_lv<4>) (zext_ln33_fu_408_p1.read());
}

void inference::thread_b2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        b2_ce0 = ap_const_logic_1;
    } else {
        b2_ce0 = ap_const_logic_0;
    }
}

void inference::thread_bitcast_ln24_fu_345_p1() {
    bitcast_ln24_fu_345_p1 = reg_271.read();
}

void inference::thread_grp_fu_251_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1.read(), ap_const_boolean_0))) {
        grp_fu_251_p0 = ap_phi_mux_sum2_0_phi_fu_233_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_251_p0 = ap_phi_mux_sum_0_phi_fu_211_p4.read();
    } else {
        grp_fu_251_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void inference::thread_grp_fu_257_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage2.read(), ap_const_boolean_0))) {
        grp_fu_257_p0 = W2_load_reg_590.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        grp_fu_257_p0 = W1_load_reg_528.read();
    } else {
        grp_fu_257_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void inference::thread_grp_fu_257_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage2.read(), ap_const_boolean_0))) {
        grp_fu_257_p1 = hidden_load_reg_595.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        grp_fu_257_p1 = input_load_reg_533.read();
    } else {
        grp_fu_257_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void inference::thread_hidden_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        hidden_address0 =  (sc_lv<4>) (zext_ln38_fu_430_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        hidden_address0 = hidden_addr_reg_493.read();
    } else {
        hidden_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void inference::thread_hidden_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        hidden_ce0 = ap_const_logic_1;
    } else {
        hidden_ce0 = ap_const_logic_0;
    }
}

void inference::thread_hidden_d0() {
    hidden_d0 = (!and_ln24_fu_381_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln24_fu_381_p2.read()[0].to_bool())? ap_const_lv32_0: reg_271.read());
}

void inference::thread_hidden_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln17_1_reg_538_pp0_iter2_reg.read(), ap_const_lv1_1))) {
        hidden_we0 = ap_const_logic_1;
    } else {
        hidden_we0 = ap_const_logic_0;
    }
}

void inference::thread_i_1_fu_424_p2() {
    i_1_fu_424_p2 = (!ap_phi_mux_i3_0_phi_fu_244_p4.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(ap_phi_mux_i3_0_phi_fu_244_p4.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void inference::thread_i_fu_307_p2() {
    i_fu_307_p2 = (!ap_phi_mux_i_0_phi_fu_201_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(ap_phi_mux_i_0_phi_fu_201_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void inference::thread_icmp_ln13_fu_279_p2() {
    icmp_ln13_fu_279_p2 = (!j_0_reg_185.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_185.read() == ap_const_lv5_10);
}

void inference::thread_icmp_ln17_1_fu_340_p2() {
    icmp_ln17_1_fu_340_p2 = (!i_reg_512.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_512.read() == ap_const_lv10_310);
}

void inference::thread_icmp_ln17_fu_301_p2() {
    icmp_ln17_fu_301_p2 = (!ap_phi_mux_i_0_phi_fu_201_p4.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i_0_phi_fu_201_p4.read() == ap_const_lv10_310);
}

void inference::thread_icmp_ln24_1_fu_369_p2() {
    icmp_ln24_1_fu_369_p2 = (!trunc_ln24_fu_359_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln24_fu_359_p1.read() == ap_const_lv23_0);
}

void inference::thread_icmp_ln24_fu_363_p2() {
    icmp_ln24_fu_363_p2 = (!tmp_fu_349_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_349_p4.read() != ap_const_lv8_FF);
}

void inference::thread_icmp_ln31_fu_396_p2() {
    icmp_ln31_fu_396_p2 = (!j1_0_reg_218.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(j1_0_reg_218.read() == ap_const_lv4_A);
}

void inference::thread_icmp_ln35_1_fu_475_p2() {
    icmp_ln35_1_fu_475_p2 = (!i_1_reg_574.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_574.read() == ap_const_lv5_10);
}

void inference::thread_icmp_ln35_fu_418_p2() {
    icmp_ln35_fu_418_p2 = (!ap_phi_mux_i3_0_phi_fu_244_p4.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_i3_0_phi_fu_244_p4.read() == ap_const_lv5_10);
}

void inference::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<10>) (zext_ln20_fu_313_p1.read());
}

void inference::thread_input_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void inference::thread_j_1_fu_402_p2() {
    j_1_fu_402_p2 = (!j1_0_reg_218.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(j1_0_reg_218.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void inference::thread_j_fu_285_p2() {
    j_fu_285_p2 = (!j_0_reg_185.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j_0_reg_185.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void inference::thread_or_ln24_fu_375_p2() {
    or_ln24_fu_375_p2 = (icmp_ln24_1_fu_369_p2.read() | icmp_ln24_fu_363_p2.read());
}

void inference::thread_output_r_address0() {
    output_r_address0 = output_addr_reg_555.read();
}

void inference::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void inference::thread_output_r_d0() {
    output_r_d0 = reg_271.read();
}

void inference::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln35_1_reg_600_pp1_iter2_reg.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void inference::thread_tmp_6_fu_318_p3() {
    tmp_6_fu_318_p3 = esl_concat<10,4>(ap_phi_mux_i_0_phi_fu_201_p4.read(), ap_const_lv4_0);
}

void inference::thread_tmp_7_fu_435_p3() {
    tmp_7_fu_435_p3 = esl_concat<5,3>(ap_phi_mux_i3_0_phi_fu_244_p4.read(), ap_const_lv3_0);
}

void inference::thread_tmp_8_fu_447_p3() {
    tmp_8_fu_447_p3 = esl_concat<5,1>(ap_phi_mux_i3_0_phi_fu_244_p4.read(), ap_const_lv1_0);
}

void inference::thread_tmp_fu_349_p4() {
    tmp_fu_349_p4 = bitcast_ln24_fu_345_p1.read().range(30, 23);
}

void inference::thread_trunc_ln24_fu_359_p1() {
    trunc_ln24_fu_359_p1 = bitcast_ln24_fu_345_p1.read().range(23-1, 0);
}

void inference::thread_zext_ln15_1_fu_297_p1() {
    zext_ln15_1_fu_297_p1 = esl_zext<15,5>(j_0_reg_185.read());
}

void inference::thread_zext_ln15_fu_291_p1() {
    zext_ln15_fu_291_p1 = esl_zext<64,5>(j_0_reg_185.read());
}

void inference::thread_zext_ln20_1_fu_326_p1() {
    zext_ln20_1_fu_326_p1 = esl_zext<15,14>(tmp_6_fu_318_p3.read());
}

void inference::thread_zext_ln20_2_fu_335_p1() {
    zext_ln20_2_fu_335_p1 = esl_zext<64,15>(add_ln20_fu_330_p2.read());
}

void inference::thread_zext_ln20_fu_313_p1() {
    zext_ln20_fu_313_p1 = esl_zext<64,10>(ap_phi_mux_i_0_phi_fu_201_p4.read());
}

void inference::thread_zext_ln33_1_fu_414_p1() {
    zext_ln33_1_fu_414_p1 = esl_zext<9,4>(j1_0_reg_218.read());
}

void inference::thread_zext_ln33_fu_408_p1() {
    zext_ln33_fu_408_p1 = esl_zext<64,4>(j1_0_reg_218.read());
}

void inference::thread_zext_ln38_1_fu_443_p1() {
    zext_ln38_1_fu_443_p1 = esl_zext<9,8>(tmp_7_fu_435_p3.read());
}

void inference::thread_zext_ln38_2_fu_455_p1() {
    zext_ln38_2_fu_455_p1 = esl_zext<9,6>(tmp_8_fu_447_p3.read());
}

void inference::thread_zext_ln38_3_fu_470_p1() {
    zext_ln38_3_fu_470_p1 = esl_zext<64,9>(add_ln38_1_fu_465_p2.read());
}

void inference::thread_zext_ln38_fu_430_p1() {
    zext_ln38_fu_430_p1 = esl_zext<64,5>(ap_phi_mux_i3_0_phi_fu_244_p4.read());
}

void inference::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln13_fu_279_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln17_fu_301_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln17_fu_301_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 64 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 128 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(icmp_ln31_fu_396_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln35_fu_418_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln35_fu_418_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state32;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp1_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state32;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            }
            break;
        case 8192 : 
            if (esl_seteq<1,1,1>(ap_block_pp1_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            }
            break;
        case 16384 : 
            if (esl_seteq<1,1,1>(ap_block_pp1_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            }
            break;
        case 32768 : 
            if (esl_seteq<1,1,1>(ap_block_pp1_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<17>) ("XXXXXXXXXXXXXXXXX");
            break;
    }
}

void inference::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_address0\" :  \"" << input_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"input_r_ce0\" :  \"" << input_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"input_r_q0\" :  \"" << input_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_address0\" :  \"" << output_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_ce0\" :  \"" << output_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_we0\" :  \"" << output_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"output_r_d0\" :  \"" << output_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

