// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inference,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.225000,HLS_SYN_LAT=63798,HLS_SYN_TPT=none,HLS_SYN_MEM=33,HLS_SYN_DSP=3,HLS_SYN_FF=1050,HLS_SYN_LUT=1191,HLS_VERSION=2020_1}" *)

module inference (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_pp0_stage0 = 17'd8;
parameter    ap_ST_fsm_pp0_stage1 = 17'd16;
parameter    ap_ST_fsm_pp0_stage2 = 17'd32;
parameter    ap_ST_fsm_pp0_stage3 = 17'd64;
parameter    ap_ST_fsm_pp0_stage4 = 17'd128;
parameter    ap_ST_fsm_state17 = 17'd256;
parameter    ap_ST_fsm_state18 = 17'd512;
parameter    ap_ST_fsm_state19 = 17'd1024;
parameter    ap_ST_fsm_pp1_stage0 = 17'd2048;
parameter    ap_ST_fsm_pp1_stage1 = 17'd4096;
parameter    ap_ST_fsm_pp1_stage2 = 17'd8192;
parameter    ap_ST_fsm_pp1_stage3 = 17'd16384;
parameter    ap_ST_fsm_pp1_stage4 = 17'd32768;
parameter    ap_ST_fsm_state32 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] b1_address0;
reg    b1_ce0;
wire   [31:0] b1_q0;
wire   [13:0] W1_address0;
reg    W1_ce0;
wire   [31:0] W1_q0;
wire   [3:0] b2_address0;
reg    b2_ce0;
wire   [31:0] b2_q0;
wire   [7:0] W2_address0;
reg    W2_ce0;
wire   [31:0] W2_q0;
reg   [9:0] i_0_reg_197;
reg   [31:0] sum_0_reg_208;
reg   [31:0] sum2_0_reg_230;
reg   [4:0] i3_0_reg_240;
wire   [31:0] grp_fu_257_p2;
reg   [31:0] reg_266;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state14_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln17_reg_508;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_state20_pp1_stage0_iter0;
wire    ap_block_state25_pp1_stage0_iter1;
wire    ap_block_state30_pp1_stage0_iter2;
wire    ap_block_pp1_stage0_11001;
reg   [0:0] icmp_ln35_reg_570;
wire   [31:0] grp_fu_251_p2;
reg   [31:0] reg_271;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln17_reg_508_pp0_iter1_reg;
reg    ap_enable_reg_pp1_iter2;
reg   [0:0] icmp_ln35_reg_570_pp1_iter1_reg;
wire   [4:0] j_fu_285_p2;
reg   [4:0] j_reg_483;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln13_fu_279_p2;
reg   [3:0] hidden_addr_reg_493;
wire   [14:0] zext_ln15_1_fu_297_p1;
reg   [14:0] zext_ln15_1_reg_498;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln17_fu_301_p2;
reg   [0:0] icmp_ln17_reg_508_pp0_iter2_reg;
wire   [9:0] i_fu_307_p2;
reg   [9:0] i_reg_512;
reg    ap_enable_reg_pp0_iter0;
reg   [31:0] W1_load_reg_528;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state5_pp0_stage1_iter0;
wire    ap_block_state10_pp0_stage1_iter1;
wire    ap_block_state15_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] input_load_reg_533;
wire   [0:0] icmp_ln17_1_fu_340_p2;
reg   [0:0] icmp_ln17_1_reg_538;
reg   [0:0] icmp_ln17_1_reg_538_pp0_iter2_reg;
wire   [3:0] j_1_fu_402_p2;
reg   [3:0] j_1_reg_545;
wire    ap_CS_fsm_state18;
wire   [0:0] icmp_ln31_fu_396_p2;
reg   [3:0] output_addr_reg_555;
wire   [8:0] zext_ln33_1_fu_414_p1;
reg   [8:0] zext_ln33_1_reg_560;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln35_fu_418_p2;
reg   [0:0] icmp_ln35_reg_570_pp1_iter2_reg;
wire   [4:0] i_1_fu_424_p2;
reg   [4:0] i_1_reg_574;
reg    ap_enable_reg_pp1_iter0;
reg   [31:0] W2_load_reg_590;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_state21_pp1_stage1_iter0;
wire    ap_block_state26_pp1_stage1_iter1;
wire    ap_block_state31_pp1_stage1_iter2;
wire    ap_block_pp1_stage1_11001;
wire   [31:0] hidden_q0;
reg   [31:0] hidden_load_reg_595;
wire   [0:0] icmp_ln35_1_fu_475_p2;
reg   [0:0] icmp_ln35_1_reg_600;
reg   [0:0] icmp_ln35_1_reg_600_pp1_iter2_reg;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
wire    ap_block_state8_pp0_stage4_iter0;
wire    ap_block_state13_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_subdone;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state6_pp0_stage2_iter0;
wire    ap_block_state11_pp0_stage2_iter1;
wire    ap_block_state16_pp0_stage2_iter2;
wire    ap_block_pp0_stage2_subdone;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state20;
wire    ap_block_state24_pp1_stage4_iter0;
wire    ap_block_state29_pp1_stage4_iter1;
wire    ap_block_pp1_stage4_subdone;
wire    ap_CS_fsm_pp1_stage4;
wire    ap_block_pp1_stage1_subdone;
reg   [3:0] hidden_address0;
reg    hidden_ce0;
reg    hidden_we0;
wire   [31:0] hidden_d0;
reg   [4:0] j_0_reg_185;
wire    ap_CS_fsm_state17;
reg   [9:0] ap_phi_mux_i_0_phi_fu_201_p4;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_sum_0_phi_fu_211_p4;
wire    ap_block_pp0_stage1;
reg   [3:0] j1_0_reg_218;
wire    ap_CS_fsm_state32;
reg   [31:0] ap_phi_mux_sum2_0_phi_fu_233_p4;
wire    ap_block_pp1_stage1;
reg   [4:0] ap_phi_mux_i3_0_phi_fu_244_p4;
wire    ap_block_pp1_stage0;
wire   [63:0] zext_ln15_fu_291_p1;
wire   [63:0] zext_ln20_2_fu_335_p1;
wire   [63:0] zext_ln20_fu_313_p1;
wire   [63:0] zext_ln33_fu_408_p1;
wire   [63:0] zext_ln38_3_fu_470_p1;
wire   [63:0] zext_ln38_fu_430_p1;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage2;
reg   [31:0] grp_fu_251_p0;
reg   [31:0] grp_fu_257_p0;
reg   [31:0] grp_fu_257_p1;
wire    ap_CS_fsm_pp1_stage2;
wire    ap_block_pp1_stage2;
wire   [13:0] tmp_6_fu_318_p3;
wire   [14:0] zext_ln20_1_fu_326_p1;
wire   [14:0] add_ln20_fu_330_p2;
wire   [31:0] bitcast_ln24_fu_345_p1;
wire   [7:0] tmp_fu_349_p4;
wire   [22:0] trunc_ln24_fu_359_p1;
wire   [0:0] icmp_ln24_1_fu_369_p2;
wire   [0:0] icmp_ln24_fu_363_p2;
wire   [0:0] or_ln24_fu_375_p2;
wire   [0:0] grp_fu_261_p2;
wire   [0:0] and_ln24_fu_381_p2;
wire   [7:0] tmp_7_fu_435_p3;
wire   [5:0] tmp_8_fu_447_p3;
wire   [8:0] zext_ln38_2_fu_455_p1;
wire   [8:0] zext_ln38_1_fu_443_p1;
wire   [8:0] add_ln38_fu_459_p2;
wire   [8:0] add_ln38_1_fu_465_p2;
wire    ap_block_pp0_stage1_00001;
reg   [16:0] ap_NS_fsm;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_state7_pp0_stage3_iter0;
wire    ap_block_state12_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage3_11001;
wire    ap_block_pp0_stage4_11001;
wire    ap_block_state22_pp1_stage2_iter0;
wire    ap_block_state27_pp1_stage2_iter1;
wire    ap_block_pp1_stage2_subdone;
wire    ap_block_pp1_stage2_11001;
wire    ap_block_state23_pp1_stage3_iter0;
wire    ap_block_state28_pp1_stage3_iter1;
wire    ap_block_pp1_stage3_subdone;
wire    ap_block_pp1_stage3_11001;
wire    ap_block_pp1_stage4_11001;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
end

inference_b1 #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
b1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b1_address0),
    .ce0(b1_ce0),
    .q0(b1_q0)
);

inference_W1 #(
    .DataWidth( 32 ),
    .AddressRange( 12544 ),
    .AddressWidth( 14 ))
W1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W1_address0),
    .ce0(W1_ce0),
    .q0(W1_q0)
);

inference_b2 #(
    .DataWidth( 32 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
b2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b2_address0),
    .ce0(b2_ce0),
    .q0(b2_q0)
);

inference_W2 #(
    .DataWidth( 32 ),
    .AddressRange( 160 ),
    .AddressWidth( 8 ))
W2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(W2_address0),
    .ce0(W2_ce0),
    .q0(W2_q0)
);

inference_hidden #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
hidden_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(hidden_address0),
    .ce0(hidden_ce0),
    .we0(hidden_we0),
    .d0(hidden_d0),
    .q0(hidden_q0)
);

inference_fadd_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
inference_fadd_32bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_251_p0),
    .din1(reg_266),
    .ce(1'b1),
    .dout(grp_fu_251_p2)
);

inference_fmul_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
inference_fmul_32cud_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_257_p0),
    .din1(grp_fu_257_p1),
    .ce(1'b1),
    .dout(grp_fu_257_p2)
);

inference_fcmp_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
inference_fcmp_32dEe_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_271),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_261_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state20) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage4_subdone) & (1'b1 == ap_CS_fsm_pp1_stage4))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp1_stage4_subdone) & (1'b1 == ap_CS_fsm_pp1_stage4)) | ((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1)))) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if ((1'b1 == ap_CS_fsm_state19)) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln35_reg_570 == 1'd0))) begin
        i3_0_reg_240 <= i_1_reg_574;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        i3_0_reg_240 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_508 == 1'd0))) begin
        i_0_reg_197 <= i_reg_512;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_0_reg_197 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln13_fu_279_p2 == 1'd1))) begin
        j1_0_reg_218 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state32)) begin
        j1_0_reg_218 <= j_1_reg_545;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        j_0_reg_185 <= j_reg_483;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        j_0_reg_185 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln35_reg_570_pp1_iter2_reg == 1'd0))) begin
        sum2_0_reg_230 <= reg_271;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        sum2_0_reg_230 <= b2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln17_reg_508_pp0_iter2_reg == 1'd0))) begin
        sum_0_reg_208 <= reg_271;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        sum_0_reg_208 <= b1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln17_reg_508 == 1'd0))) begin
        W1_load_reg_528 <= W1_q0;
        input_load_reg_533 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (icmp_ln35_reg_570 == 1'd0))) begin
        W2_load_reg_590 <= W2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln13_fu_279_p2 == 1'd0))) begin
        hidden_addr_reg_493 <= zext_ln15_fu_291_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln35_reg_570 == 1'd0))) begin
        hidden_load_reg_595 <= hidden_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        i_1_reg_574 <= i_1_fu_424_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        i_reg_512 <= i_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_508 == 1'd0))) begin
        icmp_ln17_1_reg_538 <= icmp_ln17_1_fu_340_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln17_1_reg_538_pp0_iter2_reg <= icmp_ln17_1_reg_538;
        icmp_ln17_reg_508 <= icmp_ln17_fu_301_p2;
        icmp_ln17_reg_508_pp0_iter1_reg <= icmp_ln17_reg_508;
        icmp_ln17_reg_508_pp0_iter2_reg <= icmp_ln17_reg_508_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln35_reg_570 == 1'd0))) begin
        icmp_ln35_1_reg_600 <= icmp_ln35_1_fu_475_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln35_1_reg_600_pp1_iter2_reg <= icmp_ln35_1_reg_600;
        icmp_ln35_reg_570 <= icmp_ln35_fu_418_p2;
        icmp_ln35_reg_570_pp1_iter1_reg <= icmp_ln35_reg_570;
        icmp_ln35_reg_570_pp1_iter2_reg <= icmp_ln35_reg_570_pp1_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        j_1_reg_545 <= j_1_fu_402_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        j_reg_483 <= j_fu_285_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (icmp_ln31_fu_396_p2 == 1'd0))) begin
        output_addr_reg_555 <= zext_ln33_fu_408_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_508 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln35_reg_570 == 1'd0)))) begin
        reg_266 <= grp_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln17_reg_508_pp0_iter1_reg == 1'd0)) | ((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln35_reg_570_pp1_iter1_reg == 1'd0)))) begin
        reg_271 <= grp_fu_251_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln15_1_reg_498[4 : 0] <= zext_ln15_1_fu_297_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        zext_ln33_1_reg_560[3 : 0] <= zext_ln33_1_fu_414_p1[3 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        W1_ce0 = 1'b1;
    end else begin
        W1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        W2_ce0 = 1'b1;
    end else begin
        W2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln17_fu_301_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln35_fu_418_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state20 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state20 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_396_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln35_reg_570 == 1'd0))) begin
        ap_phi_mux_i3_0_phi_fu_244_p4 = i_1_reg_574;
    end else begin
        ap_phi_mux_i3_0_phi_fu_244_p4 = i3_0_reg_240;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln17_reg_508 == 1'd0))) begin
        ap_phi_mux_i_0_phi_fu_201_p4 = i_reg_512;
    end else begin
        ap_phi_mux_i_0_phi_fu_201_p4 = i_0_reg_197;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (icmp_ln35_reg_570_pp1_iter2_reg == 1'd0))) begin
        ap_phi_mux_sum2_0_phi_fu_233_p4 = reg_271;
    end else begin
        ap_phi_mux_sum2_0_phi_fu_233_p4 = sum2_0_reg_230;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln17_reg_508_pp0_iter2_reg == 1'd0))) begin
        ap_phi_mux_sum_0_phi_fu_211_p4 = reg_271;
    end else begin
        ap_phi_mux_sum_0_phi_fu_211_p4 = sum_0_reg_208;
    end
end

always @ (*) begin
    if (((icmp_ln31_fu_396_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        b1_ce0 = 1'b1;
    end else begin
        b1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        b2_ce0 = 1'b1;
    end else begin
        b2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1))) begin
        grp_fu_251_p0 = ap_phi_mux_sum2_0_phi_fu_233_p4;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_251_p0 = ap_phi_mux_sum_0_phi_fu_211_p4;
    end else begin
        grp_fu_251_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_257_p0 = W2_load_reg_590;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_257_p0 = W1_load_reg_528;
    end else begin
        grp_fu_257_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_fu_257_p1 = hidden_load_reg_595;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        grp_fu_257_p1 = input_load_reg_533;
    end else begin
        grp_fu_257_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        hidden_address0 = zext_ln38_fu_430_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        hidden_address0 = hidden_addr_reg_493;
    end else begin
        hidden_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        hidden_ce0 = 1'b1;
    end else begin
        hidden_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln17_1_reg_538_pp0_iter2_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        hidden_we0 = 1'b1;
    end else begin
        hidden_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln35_1_reg_600_pp1_iter2_reg == 1'd1) & (1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln13_fu_279_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln17_fu_301_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln17_fu_301_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1)) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else if (((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state18 : begin
            if (((icmp_ln31_fu_396_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln35_fu_418_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (icmp_ln35_fu_418_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((~((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0)) & (1'b0 == ap_block_pp1_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else if (((1'b0 == ap_block_pp1_stage1_subdone) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((1'b0 == ap_block_pp1_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp1_stage3 : begin
            if ((1'b0 == ap_block_pp1_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end
        end
        ap_ST_fsm_pp1_stage4 : begin
            if ((1'b0 == ap_block_pp1_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage4;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W1_address0 = zext_ln20_2_fu_335_p1;

assign W2_address0 = zext_ln38_3_fu_470_p1;

assign add_ln20_fu_330_p2 = (zext_ln15_1_reg_498 + zext_ln20_1_fu_326_p1);

assign add_ln38_1_fu_465_p2 = (add_ln38_fu_459_p2 + zext_ln33_1_reg_560);

assign add_ln38_fu_459_p2 = (zext_ln38_2_fu_455_p1 + zext_ln38_1_fu_443_p1);

assign and_ln24_fu_381_p2 = (or_ln24_fu_375_p2 & grp_fu_261_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp1_stage4 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd16];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp1_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp1_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp1_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp1_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp1_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp1_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp1_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign b1_address0 = zext_ln15_fu_291_p1;

assign b2_address0 = zext_ln33_fu_408_p1;

assign bitcast_ln24_fu_345_p1 = reg_271;

assign hidden_d0 = ((and_ln24_fu_381_p2[0:0] === 1'b1) ? 32'd0 : reg_271);

assign i_1_fu_424_p2 = (ap_phi_mux_i3_0_phi_fu_244_p4 + 5'd1);

assign i_fu_307_p2 = (ap_phi_mux_i_0_phi_fu_201_p4 + 10'd1);

assign icmp_ln13_fu_279_p2 = ((j_0_reg_185 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln17_1_fu_340_p2 = ((i_reg_512 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_301_p2 = ((ap_phi_mux_i_0_phi_fu_201_p4 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln24_1_fu_369_p2 = ((trunc_ln24_fu_359_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln24_fu_363_p2 = ((tmp_fu_349_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_396_p2 = ((j1_0_reg_218 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln35_1_fu_475_p2 = ((i_1_reg_574 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_418_p2 = ((ap_phi_mux_i3_0_phi_fu_244_p4 == 5'd16) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln20_fu_313_p1;

assign j_1_fu_402_p2 = (j1_0_reg_218 + 4'd1);

assign j_fu_285_p2 = (j_0_reg_185 + 5'd1);

assign or_ln24_fu_375_p2 = (icmp_ln24_fu_363_p2 | icmp_ln24_1_fu_369_p2);

assign output_r_address0 = output_addr_reg_555;

assign output_r_d0 = reg_271;

assign tmp_6_fu_318_p3 = {{ap_phi_mux_i_0_phi_fu_201_p4}, {4'd0}};

assign tmp_7_fu_435_p3 = {{ap_phi_mux_i3_0_phi_fu_244_p4}, {3'd0}};

assign tmp_8_fu_447_p3 = {{ap_phi_mux_i3_0_phi_fu_244_p4}, {1'd0}};

assign tmp_fu_349_p4 = {{bitcast_ln24_fu_345_p1[30:23]}};

assign trunc_ln24_fu_359_p1 = bitcast_ln24_fu_345_p1[22:0];

assign zext_ln15_1_fu_297_p1 = j_0_reg_185;

assign zext_ln15_fu_291_p1 = j_0_reg_185;

assign zext_ln20_1_fu_326_p1 = tmp_6_fu_318_p3;

assign zext_ln20_2_fu_335_p1 = add_ln20_fu_330_p2;

assign zext_ln20_fu_313_p1 = ap_phi_mux_i_0_phi_fu_201_p4;

assign zext_ln33_1_fu_414_p1 = j1_0_reg_218;

assign zext_ln33_fu_408_p1 = j1_0_reg_218;

assign zext_ln38_1_fu_443_p1 = tmp_7_fu_435_p3;

assign zext_ln38_2_fu_455_p1 = tmp_8_fu_447_p3;

assign zext_ln38_3_fu_470_p1 = add_ln38_1_fu_465_p2;

assign zext_ln38_fu_430_p1 = ap_phi_mux_i3_0_phi_fu_244_p4;

always @ (posedge ap_clk) begin
    zext_ln15_1_reg_498[14:5] <= 10'b0000000000;
    zext_ln33_1_reg_560[8:4] <= 5'b00000;
end

endmodule //inference
